hubble/urls.py
"""
Hubble application url configuration
"""
from django.urls import include, path

from core.constants import ENVIRONMENT_DEVELOPMENT
from hubble import views
from hubble_report.settings import ENV_NAME

urlpatterns = [
    path("login", views.login, name="login"),
    path("signin", views.signin, name="signin"),
    path("signout", views.signout, name="signout"),
]

if ENV_NAME == ENVIRONMENT_DEVELOPMENT:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

hubble_report/urls.py
from django.urls import path

from hubble import views

urlpatterns = [path("health-check", views.health_check)]

training/urls.py
"""
Training app url configuration
"""
from django.urls import include, path

from hubble import views as sso_view
from training import view
from training.views import (
    batch,
    induction_kit,
    sub_batch,
    sub_batch_timeline,
    timeline,
    timeline_task,
    trainee_holiday,
    user_journey,
)

handler404 = view.error_404
handler500 = view.error_500

urlpatterns = [
    path("", include("hubble.urls")),
    path("", view.home, name="training.home"),
    path("hubble-sso-callback", sso_view.callback, name="callback"),
    # Induction kit
    path(
        "induction-kit",
        induction_kit.InductionKit.as_view(),
        name="induction-kit",
    ),
    path(
        "induction-kit/<text>",
        induction_kit.induction_kit_detail,
        name="induction-kit.detail",
    ),
    # Timeline Template
    path(
        "timeline-template",
        timeline.TimelineTemplate.as_view(),
        name="timeline-template",
    ),
    path(
        "timeline-datatable",
        timeline.TimelineTemplateDataTable.as_view(),
        name="timeline-template.datatable",
    ),
    path(
        "timeline-template/create",
        timeline.create_timeline_template,
        name="timeline-template.create",
    ),
    path(
        "timeline-template/<int:pk>/show",
        timeline.timeline_template_data,
        name="timeline-template.show",
    ),
    path(
        "timeline-template/<int:pk>/edit",
        timeline.update_timeline_template,
        name="timeline-template.edit",
    ),
    path(
        "timeline-template/<int:pk>/delete",
        timeline.delete_timeline_template,
        name="timeline-template.delete",
    ),
    path(
        "timeline-template/<int:pk>",
        timeline.TimelineTemplateDetails.as_view(),
        name="timeline-template.detail",
    ),
    # Timeline Task
    path(
        "timeline-task-datatable",
        timeline_task.TimelineTemplateTaskDataTable.as_view(),
        name="timeline-task.datatable",
    ),
    path(
        "timeline-task/create",
        timeline_task.create_timeline_task,
        name="timeline-task.create",
    ),
    path(
        "timeline-task/<int:pk>/show",
        timeline_task.timeline_task_data,
        name="timeline-task.show",
    ),
    path(
        "timeline-task/<int:pk>/edit",
        timeline_task.update_timeline_task,
        name="timeline-task.edit",
    ),
    path(
        "timeline-task/<int:pk>/delete",
        timeline_task.delete_timeline_task,
        name="timeline-task.delete",
    ),
    path(
        "timeline-task/reorder",
        timeline_task.update_order,
        name="timeline-task.reorder",
    ),
    # Batch
    path("batch", batch.BatchList.as_view(), name="batch"),
    path(
        "batch-datatable",
        batch.BatchDataTable.as_view(),
        name="batch.datatable",
    ),
    path("batch/create", batch.create_batch, name="batch.create"),
    path(
        "batch/<int:pk>/show",
        batch.batch_data,
        name="batch.show",
    ),
    path(
        "batch/<int:pk>/edit",
        batch.update_batch,
        name="batch.edit",
    ),
    path(
        "batch/<int:pk>/delete",
        batch.delete_batch,
        name="batch.delete",
    ),
    path(
        "batch/<int:pk>",
        batch.BatchDetails.as_view(),
        name="batch.detail",
    ),
    # Batch Holiday
    path(
        "batch/<int:pk>/holiday",
        trainee_holiday.TraineeHolidayList.as_view(),
        name="batch.holiday",
    ),
    path(
        "trainee-holiday-datatable",
        trainee_holiday.TraineeHolidayDataTable.as_view(),
        name="holiday-datatable",
    ),
    path(
        "batch/<int:pk>/holiday/create",
        trainee_holiday.TraineeHolidayCreateView.as_view(),
        name="holiday.create",
    ),
    path(
        "holiday/<int:pk>/show",
        trainee_holiday.TraineeHolidayDataView.as_view(),
        name="holiday.show",
    ),
    path(
        "holiday/<int:pk>/edit",
        trainee_holiday.TraineeHolidayUpdateView.as_view(),
        name="holiday.edit",
    ),
    path(
        "holiday/<int:pk>/delete",
        trainee_holiday.TraineeHolidayDeleteView.as_view(),
        name="holiday.delete",
    ),
    # Sub Batch
    path(
        "sub-batch-datatable",
        sub_batch.SubBatchDataTable.as_view(),
        name="sub-batch-datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch/create",
        sub_batch.create_sub_batch,
        name="sub-batch.create",
    ),
    path(
        "sub-batch/get-timeline",
        sub_batch.get_timelines,
        name="sub-batch.get_timelines",
    ),
    path(
        "sub-batch/<int:pk>/edit",
        sub_batch.update_sub_batch,
        name="sub-batch.edit",
    ),
    path(
        "sub-batch/<int:pk>",
        sub_batch.SubBatchDetail.as_view(),
        name="sub-batch.detail",
    ),
    path(
        "sub-batch/<int:pk>/delete",
        sub_batch.delete_sub_batch,
        name="sub-batch.delete",
    ),
    path(
        "sub-batch/trainees-datatable",
        sub_batch.SubBatchTraineesDataTable.as_view(),
        name="sub-batch.trainees-datatable",
    ),
    path(
        "sub-batch/trainees/add",
        sub_batch.add_trainee,
        name="trainees.add",
    ),
    path(
        "sub-batch/trainee/<int:pk>/remove",
        sub_batch.remove_trainee,
        name="trainee.remove",
    ),
    # sub_batch_timeline
    path(
        "sub-batch/<int:pk>/timeline",
        sub_batch_timeline.SubBatchTimeline.as_view(),
        name="sub-batch.timeline",
    ),
    path(
        "sub-batch/timeline-datatable",
        sub_batch_timeline.SubBatchTimelineDataTable.as_view(),
        name="sub-batch.datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch-timeline/create",
        sub_batch_timeline.create_sub_batch_timeline,
        name="sub_batch.timeline.create",
    ),
    path(
        "sub-batch-timeline/<int:pk>/show",
        sub_batch_timeline.sub_batch_timeline_data,
        name="sub_batch.timeline.show",
    ),
    path(
        "sub-batch-timeline/<int:pk>/edit",
        sub_batch_timeline.update_sub_batch_timeline,
        name="sub_batch.timeline.edit",
    ),
    path(
        "sub-batch-timeline/reorder",
        sub_batch_timeline.update_task_sequence,
        name="sub_batch.timeline.reorder",
    ),
    path(
        "sub-batch-timeline/<int:pk>/delete",
        sub_batch_timeline.delete_sub_batch_timeline,
        name="sub_batch.timeline.delete",
    ),
    # user_reports_crud
    path(
        "user/<int:pk>",
        user_journey.TraineeJourneyView.as_view(),
        name="user_reports",
    ),
    path(
        "task/show-score",
        user_journey.show_task_score,
        name="task.show_score",
    ),
    path(
        "user/<int:pk>/update-score",  # TODO :: Change to task_id
        user_journey.update_task_score,
        name="user.update-score",
    ),
    path(
        "add-extension/<int:pk>",
        user_journey.add_extension,
        name="extension.create",
    ),
    path(
        "extension/<int:pk>/delete",
        user_journey.delete_extension,
        name="extension.delete",
    ),
    path("show-score-history", user_journey.get_mark_history, name="score_history"),
]

training/forms.py
"""
This module provides a set of classes for building forms in Django
"""
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.utils import timezone

from core.constants import PRESENT_TYPES, TASK_TYPES, USER_STATUS_INTERN
from hubble import models
from hubble.models import Assessment, TraineeHoliday


class TimelineForm(forms.ModelForm):
    """
    Timeline form is used to create or update timeline objects,
    with additional validation and customization for the form fields.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["team"].empty_label = "Select a Team"
        self.fields["name"].validators.append(MinLengthValidator(3))

    def clean(self):
        """
        The function checks if a timeline with the given ID exists and
        returns an error message if it does not.
        """
        cleaned_data = super().clean()
        if self.data.get("id") and (
            not models.Timeline.objects.filter(id=self.data.get("id")).exists()
        ):
            self.add_error(None, "You are trying to duplicate invalid template")
        return cleaned_data

    def clean_is_active(self):
        """
        This function checks if a team already has an active template
        and raises a validation error if it does.
        """
        if self.cleaned_data.get("team", None) and (self.cleaned_data["is_active"]):
            query = models.Timeline.objects.filter(
                team=self.cleaned_data["team"], is_active=True
            ).values("id")
            if (len(query)) and (query[0]["id"] != (self.instance.id)):
                raise ValidationError(
                    "Team already has an active template.",
                    code="template_in_use",
                )

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        model = models.Timeline
        fields = ("name", "team", "is_active")

        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "w-full block border border-primary-dark-30 \
                        rounded-md focus:outline-none focus:ring-transparent \
                            focus:ring-offset-0 h-9 p-2",
                    "placeholder": "Timeline name...",
                }
            ),
            "team": forms.Select(
                attrs={
                    "class": "w-full block border border-primary-dark-30 \
                        rounded-md focus:outline-none focus:ring-transparent \
                            focus:ring-offset-0 h-9 p-2 dropdown_select",
                    "placeholder": "Select Team...",
                }
            ),
            "is_active": forms.CheckboxInput(
                attrs={
                    "class": "checkbox_active cursor-pointer block border \
                        border-primary-dark-30 rounded-md w-4 mr-3 focus:outline-none \
                            focus:ring-transparent focus:ring-offset-0 h-9 p-2",
                }
            ),
        }


class TimelineTaskForm(forms.ModelForm):
    """
    Timeline task form is used to add and update the timeline task
    with the respective with the custom validations
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].validators.append(MinLengthValidator(3))

    @staticmethod
    def validate_days(value):
        """
        The function validates that a given value is greater than 0 and
        a multiple of 0.5, otherwise it raises a validation error.
        """
        if value <= 0:
            raise ValidationError(
                "Value must be greater than 0",
                code="value_cannot_be_zero",
            )
        if value % 0.5 != 0:
            raise ValidationError(
                "Value must be a multiple of 0.5",
                code="is_not_divisible_by_0.5",
            )

    days = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "w-full block border border-primary-dark-30 \
                    rounded-md focus:outline-none focus:ring-transparent \
                        focus:ring-offset-0 h-9 p-2",
                "placeholder": "No of days...",
            }
        ),
        validators=[validate_days],
    )
    present_type = forms.ChoiceField(
        error_messages={
            "invalid_choice": "Select a valid choice. "
            "That choice is not one of the available choices."
        },
        widget=forms.RadioSelect,
        choices=PRESENT_TYPES,
    )
    task_type = forms.ChoiceField(
        error_messages={
            "invalid_choice": "Select a valid choice. "
            "That choice is not one of the available choices."
        },
        widget=forms.RadioSelect,
        choices=TASK_TYPES,
    )

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        model = models.TimelineTask
        fields = ("name", "days", "present_type", "task_type")

        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "w-full block border border-primary-dark-30 \
                        rounded-md focus:outline-none focus:ring-transparent \
                            focus:ring-offset-0 h-9 p-2",
                    "placeholder": "Task Name...",
                }
            ),
        }


class BatchForm(forms.ModelForm):
    """
    Batch form is used to create and update the batch data
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].validators.append(MinLengthValidator(3))

    def clean_start_date(self):
        """
        The function checks if a selected start date is valid
        and raises a validation error if it doesn't.
        """
        if (
            models.Holiday.objects.filter(date_of_holiday=self.cleaned_data["start_date"]).exists()
            or self.cleaned_data["start_date"].weekday() == 6
        ):
            raise ValidationError(
                "The Selected date falls on a holiday, please reconsider the start date",
                code="invalid_date",
            )
        return self.cleaned_data["start_date"]

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        model = models.Batch
        fields = ("name", "start_date")

        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "w-full block border border-primary-dark-30 \
                        rounded-md focus:outline-none focus:ring-transparent \
                            focus:ring-offset-0 h-9 p-2",
                    "placeholder": "Batch Name...",
                }
            ),
            "start_date": forms.DateInput(
                attrs={
                    "class": " w-full block border border-primary-dark-30 rounded-md \
                        focus:outline-none focus:ring-transparent focus:ring-offset-0 \
                            h-9 p-2 start_date_input",
                    "placeholder": "Start Date",
                }
            ),
        }


class TraineeHolidayForm(forms.ModelForm):
    """
    Trainee holiday form is used to create and update the trainee holiday with custom validations
    """

    def clean_date_of_holiday(self):
        """
        This function checks if a holiday already exists for the given date and batch
        Raises a validation error.
        """
        id = self.data.get("id", None)  # pylint: disable=W0622
        if (
            TraineeHoliday.objects.filter(
                date_of_holiday=self.cleaned_data["date_of_holiday"],
                batch_id=self.data.get("batch_id"),
            )
            .exclude(id=id)
            .exists()
        ):
            raise ValidationError(
                "The date of holiday has already been taken.",
                code="invalid_date",
            )
        if id:
            holiday = TraineeHoliday.objects.get(id=id)
            if (
                holiday.date_of_holiday != self.cleaned_data["date_of_holiday"]
                and self.cleaned_data["date_of_holiday"] < timezone.now().date()
            ):
                raise ValidationError(
                    "The date of holiday cannot be in the past.",
                    code="invalid_date",
                )
        else:
            if self.cleaned_data["date_of_holiday"] < timezone.now().date():
                raise ValidationError(
                    "The date of holiday cannot be in the past.",
                    code="invalid_date",
                )
        return self.cleaned_data["date_of_holiday"]

    date_of_holiday = forms.DateField(
        label="Choose Date",
        widget=forms.DateInput(
            attrs={
                "class": "block border border-primary-dark-30 rounded-md mt-2.5 \
                    w-64 focus:outline-none focus:ring-transparent focus:ring-offset-0 \
                        h-9 p-2 bg-transparent w-250 start_date_input",
                "placeholder": "Choose Date",
            }
        ),
    )

    reason = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "w-full block border border-primary-dark-30 mt-2.5 rounded-md \
                    focus:outline-none focus:ring-transparent focus:ring-offset-0 h-9 p-2 \
                        bg-transparent w-250 ",
                "placeholder": "Reason For Holiday",
            }
        ),
    )

    national_holiday = forms.BooleanField(
        required=False,
        label="National Holiday",
        widget=forms.CheckboxInput(
            attrs={
                "class": "checkbox_active cursor-pointer block border border-primary-dark-30 \

training/templates/induction_kit.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %}
    Induction Kit
{% endblock title %}

{% block header %}Induction Kit{% endblock %}

{% block body %}
    <div class="flex">
        <div class="flex flex-wrap">
            {% for filename in pdf_files %}
                <a href="{% url 'induction-kit.detail' filename %}"
                   target="_blank"
                   class=" text-blue-600 text-xs sm:text-sm"
                   id="card-link">
                    <div class=" bg-white rounded-xl shadow-md overflow-hidden p-4"
                         id="card-container">
                        <div class="relative mb-4">
                            <img class="h-14 w-12 object-cover"
                                 src="{% static 'training/images/pdficon.svg' %}"
                                 alt="pdf icon"
                                 width="3rem"
                                 height="3.5rem">
                        </div>
                        <div>
                            <h4 href="#"
                                class="mt-2 text-gray-900 hover:underline text-sm sm:text-lg">{{ filename }}</h4>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

training/templates/timeline_template_detail.html
{% extends 'layouts/base.html' %}

{% block title %}
    Timeline Template Detail
{% endblock title %}

{% block header %}
    <div class="flex justify-between items-center">
        <div>
            <div class="text-dark-black text-lg mb-1 leading-none">
                <a href="{% url 'timeline-template' %}"
                   class="flex items-center text-sm text-dark-blue">
                    <div class="inline mr-1">
                        <span class="hbl hbl-left text-2xl text-dark-black/50"></span>
                    </div>
                    Back to Timeline template
                </a>
                <h4 class="text-lg text-black ">{{ timeline.name }}</h4>
            </div>
            <div class="text-dark-black-50 text-sm">
                <p class="text-sm">Current you are viewing {{ timeline.name }} timeline template</p>
            </div>
        </div>
        {% if request.user.is_admin_user %}
            <button class="text-white bg-dark-blue rounded inline-flex items-center px-3 py-1 text-base font-normal"
                    onclick="openTaskCreateModal()">
                <span class="text-xl mr-2">+</span>
                Create Task
            </button>
        {% endif %}
    </div>
{% endblock %}

{% block body %}
    <div class="jquery-modal current hidden" id="modal">
        <div class="modal py-5 rounded-xl mr-5 mt-9 bg-white jquery-modal-body">
            <p class="font-semibold text-lg mb-10" id="modalName"></p>
            <form method="post"
                  class="timeline-task-form"
                  id="timeline-task-create-form">
                <input type="hidden" name="timeline-task" id="timeline-task">
                <div class="modal-body">
                    {% csrf_token %}
                    <input type="hidden"
                           name="timeline_id"
                           value="{{ timeline.id }}"
                           id="timeline_id">
                    <div class="mb-7" id="{{ form.name.label|lower }}_group">
                        {{ form.name|show_label }}
                        {{ form.name }}
                    </div>
                    <div class="mb-7" id="{{ form.days.label|lower }}_group">
                        {{ form.days|show_label }}
                        {{ form.days }}
                    </div>
                    <div class="mb-7" id="{{ form.present_type.label|convert_to_id|lower }}_group">
                        {{ form.present_type|show_label }}
                        {{ form.present_type }}
                    </div>
                    <div class="mb-7" id="{{ form.task_type.label|convert_to_id|lower }}_group">
                        {{ form.task_type|show_label }}
                        {{ form.task_type }}
                    </div>
                </div>
                <div class="text-center mt-10">
                    <a class="cursor-pointer inline-block align-middle border border-grey px-8 py-2 rounded mr-6"
                       onclick="closeModal('modal')">Close</a>
                    <a class="cursor-pointer inline-block align-middle text-white bg-dark-blue rounded inline-flex items-center rounded px-8 py-2 text-base font-normal"
                       id="submit-btn">Submit</a>
                </div>
            </form>
        </div>
    </div>
    <table id="timeline-table"
           class="display border-0 table-with-no-border dataTable no-footer w-100"
           role="grid"
           aria-describedby="timeline-table_info">
        <tbody id="sortable">
        </tbody>
    </table>
{% endblock %}

{% block script %}
    <script>
        let copy_seleted = [];
        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#timeline-table'),
                "{% url 'timeline-task.datatable' %}", {
                    serverSide: true,
                    processing: true,
                    autoWidth: false,
                    scrollX: false,
                    order: [],
                    bPaginate: false
                }, {
                    'timeline_id': '{{ timeline.id }}',
                }
            );
            $("#sortable > tr").each(function() {
                copy_selected.push($(this).children(':first').text());
            })
        });

        $(function() {
            if ("{{ request.user.is_admin_user }}" == "True") {
                $("#sortable").sortable({
                    stop: function() {
                        var selectedData = [];
                        $("#sortable > tr").each(function() {
                            selectedData.push($(this).children(':first').children(':first').attr('data-id'));
                        })
                        if (copy_seleted.toString() !== selectedData.toString()) {
                            copy_seleted = selectedData;
                            updateOrder(copy_seleted);
                        }
                    }
                });
            }
        });

        function updateOrder(data) {
            /**
             * Updates an order using AJAX                     
             *
             * @param {Object} data - The data containing the updated order information.
             */
            $('.page-loader').show();
            $.ajax({
                type: "POST",
                url: "{% url 'timeline-task.reorder' %}",
                data: {
                    data: data,
                    timeline_id: "{{ timeline.id }}",
                },
                success: function(data) {
                    if (data.status === 'success') {
                        $('.page-loader').hide();
                        $('#timeline-table').DataTable().ajax.reload();
                        closeModal('modal');
                    }
                },
                error: function() {
                    $('.page-loader').hide();
                    alert("Something went wrong");
                },
            });
        }

        function openTaskCreateModal() {
            openBaseModal();
            $("#modalName").text('Create Task');
            $('#id_name').val('');
            $('#id_days').val('');
            $('#submit-btn').attr("onclick", "createTimelineTask()");
        }

        function createTimelineTask() {
            $('.page-loader').show();
            $.ajax({
                type: "POST",
                url: "{% url 'timeline-task.create' %}",
                data: {
                    name: $('#id_name').val(),
                    days: $('#id_days').val(),
                    present_type: $('input[name="present_type"]:checked').val(),
                    task_type: $('input[name="task_type"]:checked').val(),
                    timeline_id: $('#timeline_id').val(),
                },
                success: function(data) {
                    removeErrors();
                    $('.page-loader').hide();
                    if (data.status === 'success') {
                        $('#timeline-table').DataTable().ajax.reload();
                        closeModal('modal');
                    } else {
                        renderFormError(data);
                    }
                },
                error: function() {
                    $('.page-loader').hide();
                    alert("Something went wrong");
                },
            });
        }

        function openUpdateModel(url) {
            removeErrors();
            $("#modalName").text('Update Task');
            $('.page-loader').show();
            $('.update-form-fields-container').empty();
            $.ajax({
                type: "GET",
                url: url,
                success: function(data) {
                    $('.page-loader').hide();
                    $('input[name="id_present_type"]').attr('checked', false);
                    $('input[name="id_task_type"]').attr('checked', false);
                    $('#timeline-task').val(data.timeline_task.id);
                    $('#id_name').val(data.timeline_task.name);
                    $('#id_days').val(data.timeline_task.days);
                    $('input[name="present_type"][value="' + data.timeline_task.present_type + '"]').prop('checked', true);
                    $('input[name="task_type"][value="' + data.timeline_task.task_type + '"]').prop('checked', true);
                    $('#submit-btn').attr("onclick", "updateTimeline()");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert(jqXHR.responseJSON.message);
                    $('.page-loader').hide();
                },
            });
            document.getElementById("modal").classList.remove("hidden");
            document.getElementById("modal").classList.add("blocker");
        }

        function updateTimeline() {
            $('.page-loader').show();
            $.ajax({
                type: "POST",
                url: "/timeline-task/" + $("#timeline-task").val() + "/edit", //TODO
                data: {
                    name: $('#id_name').val(),
                    days: $('#id_days').val(),
                    present_type: $('input[name="present_type"]:checked').val(),
                    task_type: $('input[name="task_type"]:checked').val(),
                },
                success: function(data) {
                    removeErrors();
                    $('.page-loader').hide();
                    if (data.status === 'success') {
                        $('#timeline-table').DataTable().ajax.reload();
                        closeModal('modal');
                    } else {
                        renderFormError(data);
                    }
                },
                error: function() {
                    $('.page-loader').hide();
                    alert("Something went wrong");
                },
            });
        }

        function deleteTimeline(url) {
            let text = 'Are you sure do you want to delete';
            if (confirm(text) == true) {
                $('.page-loader').show();
                $.ajax({
                    type: "DELETE",
                    url: url,
                    success: function(data) {
                        $('#timeline-table').DataTable().ajax.reload();
                        $('.page-loader').hide();
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        alert(jqXHR.responseJSON.message);
                        $('.page-loader').hide();
                    },
                });
            }
        }
    </script>
{% endblock %}