hubble/urls.py
"""
Hubble application url configuration
"""
from django.urls import include, path

from core.constants import ENVIRONMENT_DEVELOPMENT
from hubble import views
from hubble_report.settings import ENV_NAME

urlpatterns = [
    path("login", views.login, name="login"),
    path("signin", views.signin, name="signin"),
    path("signout", views.signout, name="signout"),
]

if ENV_NAME == ENVIRONMENT_DEVELOPMENT:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

hubble_report/urls.py
from django.urls import path

from hubble import views

urlpatterns = [path("health-check", views.health_check)]

training/urls.py
"""
Training app url configuration
"""
from django.urls import include, path

from hubble import views as sso_view
from training import view
from training.views import (
    batch,
    induction_kit,
    sub_batch,
    sub_batch_timeline,
    timeline,
    timeline_task,
    trainee_holiday,
    user_journey,
)

handler404 = view.error_404
handler500 = view.error_500

urlpatterns = [
    path("", include("hubble.urls")),
    path("", view.home, name="training.home"),
    path("hubble-sso-callback", sso_view.callback, name="callback"),
    # Induction kit
    path(
        "induction-kit",
        induction_kit.InductionKit.as_view(),
        name="induction-kit",
    ),
    path(
        "induction-kit/<text>",
        induction_kit.induction_kit_detail,
        name="induction-kit.detail",
    ),
    # Timeline Template
    path(
        "timeline-template",
        timeline.TimelineTemplate.as_view(),
        name="timeline-template",
    ),
    path(
        "timeline-datatable",
        timeline.TimelineTemplateDataTable.as_view(),
        name="timeline-template.datatable",
    ),
    path(
        "timeline-template/create",
        timeline.create_timeline_template,
        name="timeline-template.create",
    ),
    path(
        "timeline-template/<int:pk>/show",
        timeline.timeline_template_data,
        name="timeline-template.show",
    ),
    path(
        "timeline-template/<int:pk>/edit",
        timeline.update_timeline_template,
        name="timeline-template.edit",
    ),
    path(
        "timeline-template/<int:pk>/delete",
        timeline.delete_timeline_template,
        name="timeline-template.delete",
    ),
    path(
        "timeline-template/<int:pk>",
        timeline.TimelineTemplateDetails.as_view(),
        name="timeline-template.detail",
    ),
    # Timeline Task
    path(
        "timeline-task-datatable",
        timeline_task.TimelineTemplateTaskDataTable.as_view(),
        name="timeline-task.datatable",
    ),
    path(
        "timeline-task/create",
        timeline_task.create_timeline_task,
        name="timeline-task.create",
    ),
    path(
        "timeline-task/<int:pk>/show",
        timeline_task.timeline_task_data,
        name="timeline-task.show",
    ),
    path(
        "timeline-task/<int:pk>/edit",
        timeline_task.update_timeline_task,
        name="timeline-task.edit",
    ),
    path(
        "timeline-task/<int:pk>/delete",
        timeline_task.delete_timeline_task,
        name="timeline-task.delete",
    ),
    path(
        "timeline-task/reorder",
        timeline_task.update_order,
        name="timeline-task.reorder",
    ),
    # Batch
    path("batch", batch.BatchList.as_view(), name="batch"),
    path(
        "batch-datatable",
        batch.BatchDataTable.as_view(),
        name="batch.datatable",
    ),
    path("batch/create", batch.create_batch, name="batch.create"),
    path(
        "batch/<int:pk>/show",
        batch.batch_data,
        name="batch.show",
    ),
    path(
        "batch/<int:pk>/edit",
        batch.update_batch,
        name="batch.edit",
    ),
    path(
        "batch/<int:pk>/delete",
        batch.delete_batch,
        name="batch.delete",
    ),
    path(
        "batch/<int:pk>",
        batch.BatchDetails.as_view(),
        name="batch.detail",
    ),
    # Batch Holiday
    path(
        "batch/<int:pk>/holiday",
        trainee_holiday.TraineeHolidayList.as_view(),
        name="batch.holiday",
    ),
    path(
        "trainee-holiday-datatable",
        trainee_holiday.TraineeHolidayDataTable.as_view(),
        name="holiday-datatable",
    ),
    path(
        "batch/<int:pk>/holiday/create",
        trainee_holiday.TraineeHolidayCreateView.as_view(),
        name="holiday.create",
    ),
    path(
        "holiday/<int:pk>/show",
        trainee_holiday.TraineeHolidayDataView.as_view(),
        name="holiday.show",
    ),
    path(
        "holiday/<int:pk>/edit",
        trainee_holiday.TraineeHolidayUpdateView.as_view(),
        name="holiday.edit",
    ),
    path(
        "holiday/<int:pk>/delete",
        trainee_holiday.TraineeHolidayDeleteView.as_view(),
        name="holiday.delete",
    ),
    # Sub Batch
    path(
        "sub-batch-datatable",
        sub_batch.SubBatchDataTable.as_view(),
        name="sub-batch-datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch/create",
        sub_batch.create_sub_batch,
        name="sub-batch.create",
    ),
    path(
        "sub-batch/get-timeline",
        sub_batch.get_timelines,
        name="sub-batch.get_timelines",
    ),
    path(
        "sub-batch/<int:pk>/edit",
        sub_batch.update_sub_batch,
        name="sub-batch.edit",
    ),
    path(
        "sub-batch/<int:pk>",
        sub_batch.SubBatchDetail.as_view(),
        name="sub-batch.detail",
    ),
    path(
        "sub-batch/<int:pk>/delete",
        sub_batch.delete_sub_batch,
        name="sub-batch.delete",
    ),
    path(
        "sub-batch/trainees-datatable",
        sub_batch.SubBatchTraineesDataTable.as_view(),
        name="sub-batch.trainees-datatable",
    ),
    path(
        "sub-batch/trainees/add",
        sub_batch.add_trainee,
        name="trainees.add",
    ),
    path(
        "sub-batch/trainee/<int:pk>/remove",
        sub_batch.remove_trainee,
        name="trainee.remove",
    ),
    # sub_batch_timeline
    path(
        "sub-batch/<int:pk>/timeline",
        sub_batch_timeline.SubBatchTimeline.as_view(),
        name="sub-batch.timeline",
    ),
    path(
        "sub-batch/timeline-datatable",
        sub_batch_timeline.SubBatchTimelineDataTable.as_view(),
        name="sub-batch.datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch-timeline/create",
        sub_batch_timeline.create_sub_batch_timeline,
        name="sub_batch.timeline.create",
    ),
    path(
        "sub-batch-timeline/<int:pk>/show",
        sub_batch_timeline.sub_batch_timeline_data,
        name="sub_batch.timeline.show",
    ),
    path(
        "sub-batch-timeline/<int:pk>/edit",
        sub_batch_timeline.update_sub_batch_timeline,
        name="sub_batch.timeline.edit",
    ),
    path(
        "sub-batch-timeline/reorder",
        sub_batch_timeline.update_task_sequence,
        name="sub_batch.timeline.reorder",
    ),
    path(
        "sub-batch-timeline/<int:pk>/delete",
        sub_batch_timeline.delete_sub_batch_timeline,
        name="sub_batch.timeline.delete",
    ),
    # user_reports_crud
    path(
        "user/<int:pk>",
        user_journey.TraineeJourneyView.as_view(),
        name="user_reports",
    ),
    path(
        "task/show-score",
        user_journey.show_task_score,
        name="task.show_score",
    ),
    path(
        "user/<int:pk>/update-score",  # TODO :: Change to task_id
        user_journey.update_task_score,
        name="user.update-score",
    ),
    path(
        "add-extension/<int:pk>",
        user_journey.add_extension,
        name="extension.create",
    ),
    path(
        "extension/<int:pk>/delete",
        user_journey.delete_extension,
        name="extension.delete",
    ),
    path("show-score-history", user_journey.get_mark_history, name="score_history"),
]

hubble/models/assessment.py
"""
The Assessment class is used to store the assessment report of a trainee
"""
from django.db import models

from core import db

from .extension import Extension
from .sub_batch import SubBatch
from .sub_batch_timeline_task import SubBatchTaskTimeline
from .user import User


class Assessment(db.SoftDeleteWithBaseModel):
    """
    Store the assessment report of the trainee
    """

    sub_batch = models.ForeignKey(SubBatch, on_delete=models.CASCADE, related_name="assessments")
    task = models.ForeignKey(
        SubBatchTaskTimeline,
        on_delete=models.CASCADE,
        null=True,
        related_name="assessments",
    )
    extension = models.ForeignKey(
        Extension,
        on_delete=models.CASCADE,
        null=True,
        related_name="assessments",
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="assessments")
    score = models.IntegerField(null=True, blank=True)
    is_retry = models.BooleanField(default=False)
    comment = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="created_assessments",
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="updated_assessments", null=True
    )
    is_retry_needed = models.BooleanField(default=False, verbose_name="Is retry needed")
    present_status = models.BooleanField(default=True, verbose_name="Present status")

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        db_table = "assessments"

hubble/models/sub_batch.py
"""
The SubBatch class represents a sub-batch of data with various details
"""
from django.db import models

from core import db


class SubBatch(db.SoftDeleteWithBaseModel):
    """
    Store the sub-batch data and it details
    """

    name = models.CharField(max_length=250)
    batch = models.ForeignKey(
        "hubble.Batch",
        on_delete=models.CASCADE,
        related_name="sub_batches",
    )
    team = models.ForeignKey("hubble.Team", on_delete=models.CASCADE)
    primary_mentor = models.ForeignKey(
        "hubble.User",
        on_delete=models.CASCADE,
        related_name="primary_sub_batches",
    )
    secondary_mentors = models.ManyToManyField("hubble.User", related_name="secondary_sub_batches")
    start_date = models.DateField()
    timeline = models.ForeignKey(
        "hubble.Timeline", on_delete=models.CASCADE, related_name="sub_batches"
    )
    created_by = models.ForeignKey("hubble.User", on_delete=models.CASCADE)

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        db_table = "sub_batches"

    def __str__(self):
        return str(self.name)

hubble/models/timeline.py
"""
The Timeline class is a Django model that represents a timeline
"""
from django.db import models

from core import db


class Timeline(db.SoftDeleteWithBaseModel):
    """
    Store the timeline data
    """

    name = models.CharField(max_length=255)
    team = models.ForeignKey("hubble.Team", on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False, blank=True, verbose_name="is_active")
    created_by = models.ForeignKey("hubble.User", on_delete=models.CASCADE)

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        db_table = "timelines"

    def __str__(self):
        return str(self.name)

training/views/induction_kit.py
"""
Django view and a function for serving PDF files from a static folder, with 
authentication required for accessing the view
"""
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.views.generic import TemplateView


class InductionKit(LoginRequiredMixin, TemplateView):
    """
    Induction Kit
    """

    template_name = "induction_kit.html"
    # Getting the list of pdf files in the static folder.
    static_path = list(settings.STATICFILES_DIRS)
    extra_context = {
        "pdf_files": [
            file
            for file in os.listdir(f"{static_path[0]}/training/pdf")
            if os.path.splitext(file)[1] == ".pdf"
        ],
    }


@login_required()
def induction_kit_detail(request, text):  # pylint: disable=unused-argument
    """
    Induction Kit Detail
    """
    static_path = list(settings.STATICFILES_DIRS)
    file_path = f"{static_path[0]}/training/pdf/{text}"
    return FileResponse(open(file_path, "rb"), content_type="application/pdf")

training/views/trainee_report.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from hubble.models import (
    SubBatchTaskTimeline,
    User,
    SubBatch,
    Assessment,
    WeekExtension,
)
from training.forms import AddReportForm
from django.http import JsonResponse
from django.db.models import Count, Subquery, OuterRef
from django.db.models import BooleanField, Case, When, Value, Q
from django.utils import timezone
from core.constants import TASK_TYPE_ASSESSMENT

class UserProfile(LoginRequiredMixin, DetailView):
    model = User
    template_name = "sub_batch/user_report.html"

    def get_context_data(self, **kwargs):
        
        latest_task_report = Assessment.objects.filter(task=OuterRef("id"),user_id=self.object.id).order_by("-id")[:1]
        latest_extended_task_report = Assessment.objects.filter(week_extension=OuterRef("id")).order_by("-id")[:1]
        subBatchId = SubBatch.objects.filter(intern_sub_batch_details__user = self.object.id).first()

        task_summary = (
            SubBatchTaskTimeline.objects.filter(
                sub_batch=subBatchId, task_type=TASK_TYPE_ASSESSMENT
            )
            .annotate(
                retries=Count("assessments__is_retry", filter=Q(assessments__user = self.object.id)) - 1,
                last_entry=Subquery(latest_task_report.values("score")),
                comment=Subquery(latest_task_report.values("comment")),
                is_retry=Subquery(latest_task_report.values("is_retry")),
                inactive_tasks = Case(
                    When(start_date__gt=timezone.now(), then=Value(True)),
                    default=Value(False),
                    output_field=BooleanField(),
                    ),
                )
                .values("id", "last_entry", "retries", "comment", "name", "is_retry", "inactive_tasks")
            )
        
        extended_task_summary = (
            WeekExtension.objects.filter(sub_batch=subBatchId, user=self.object.id).annotate(
                retries=Count("assessment__is_retry") - 1,
                last_entry=Subquery(latest_extended_task_report.values("score")),
                comment=Subquery(latest_extended_task_report.values("comment")),
                is_retry=Subquery(latest_extended_task_report.values("is_retry")),
            )
            .values("id", "last_entry", "retries", "comment", "is_retry")
        )
        
        context = super().get_context_data(**kwargs)
        context["assessment_scores"] = task_summary
        context["sub_batch"] = subBatchId
        context["form"] = AddReportForm()
        context["extension_tasks"] = extended_task_summary
        return context


def user_journey_page(request, pk):
    """
    Create User report
    """
    if request.method == "POST":
        form = AddReportForm(request.POST)
        if form.is_valid():  # Check if form is valid or not
            report = form.save(commit=False)
            report.user_id = pk 
            report.task_id = request.POST.get("task")
            report.week_extension_id = request.POST.get("extension")
            report.sub_batch = SubBatch.objects.filter(intern_sub_batch_details__user = pk).first()
            report.is_retry = True if request.POST.get("status") == "true" else False
            report.created_by = request.user
            report.save()
            return JsonResponse({"status": "success"})
        else:
            field_errors = form.errors.as_json()
            non_field_errors = form.non_field_errors().as_json()
            return JsonResponse(
                {
                    "status": "error",
                    "field_errors": field_errors,
                    "non_field_errors": non_field_errors,
                }
            )


def add_extension(request, pk):
    extension = WeekExtension.objects.create(
            sub_batch=SubBatch.objects.filter(intern_sub_batch_details__user = pk).first(),
            user=User.objects.get(id=pk),
            created_by=request.user,
        )
    return JsonResponse({"status": "success"})


def delete_extension(request, pk):
    """
    Delete Timeline Template
    Soft delete the template and record the deletion time in deleted_at field
    """
    try:
        extension = get_object_or_404(WeekExtension, id=pk)
        extension.delete()
        return JsonResponse(
            {"message": "Week extension deleted succcessfully", "status": "success"}
        )
    except Exception as e:
        return JsonResponse(
            {"message": "Error while deleting week extension!"}, status=500
        )

training/templates/sub_batch/score_table.html
<table class="display border-0 table-with-no-border dataTable no-footer overflow-hidden"
    aria-describedby="sub-batch-table_info">
    <thead>
        <th>Score</th>
        <th>Comments</th>
        <th>Present Status</th>
        <th>Is Retry Score</th>
        <th>Next Retry Suggested?</th>
        <th>Updated By</th>
        <th>Updated At</th>
    </thead>
    <tbody>
        {% for row in data %}
        <tr class="text-left">
            <td>
                {{ row.score }}
            </td>
            <td>
                {{ row.comment|default:"-" }}
            </td>
            <td>
                {% if row.present_status %} Yes {% else %} No {% endif %}
            </td>
            <td>
                {% if row.is_retry %} Yes {% else %} No {% endif %}
            </td>
            <td>
                {% if row.is_retry_needed %} Yes {% else %} No {% endif %}
            </td>
            <td>
                {{ row.updated_by.name }}
            </td>
            <td>
                {{ row.updated_at|date:'M-d-Y' }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

training/templates/sub_batch/sub_batch.html
{% extends 'layouts/base.html' %}

{% block title %}
    Sub Batch
{% endblock title %}

{% block header %}
    <div class="flex justify-between items-center">
        <div>
            <div class="text-dark-black text-lg mb-1 leading-none">Sub Batch List</div>
            <div class="text-dark-black text-lg mb-1 leading-none">
                <p class="text-sm">
                    <a href="{% url 'batch' %}" class="text-sm text-dark-blue">Batch List</a>
                    >
                    {{ batch.name }}
                </p>
                <h4 class="text-lg text-black ">{{ timeline.name|title }}</h4>
            </div>
            <div class="text-dark-black-50 text-sm">
                <p class="text-sm">Current you are viewing {{ batch.name }} batch</p>
            </div>
        </div>
        <div>
            <a href="{% url 'batch.holiday' batch.id %}"
               class="text-white h-9 bg-dark-blue rounded inline-flex items-center px-3 py-1 text-base font-normal">
                <span class="hbl hbl-calander text-xl mr-2"></span>
                Holidays
            </a>
            {% if request.user.is_admin_user %}
                <a href="{% url 'sub-batch.create' batch.id %}"
                   class="text-white h-9 bg-dark-blue rounded inline-flex items-center px-3 py-1 text-base font-normal">
                    <span class="text-xl mr-2 hbl hbl-plus"></span>
                    Create Sub Batch
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="flex mb-7 items-center">
        <div class="relative mr-5" id="sub_batch-table_filter">
            <input type="text"
                   value=""
                   name="search_project"
                   placeholder="Search by Name, Team and Timeline template"
                   class="w-397 h-10 pl-11 pr-2.5 py-3 text-sm rounded-xl text-dark-black-50 font-normal bg-mild-white focus:outline-none focus:ring-transparent focus:ring-offset-0"
                   id="search_project">
            <span class="absolute top-2 left-2"><span class="hbl hbl-search-icon text-dark-black-50 text-2xl"></span></span>
        </div>
        <div class="rounded-md bg-dark-blue-10 mr-4 header-data">
            <p class="text-center">
                <span class="font-bold text-dark-black" id="teams_count"></span>
            </p>
            <p class="text-dark-blue text-center">Teams</p>
        </div>
        <div class="rounded-md bg-dark-blue-10 mr-4 header-data">
            <p class="text-center">
                <span class="font-bold text-dark-black" id="trainees_count"></span>
            </p>
            <p class="text-dark-blue text-center">Trainees</p>
        </div>
    </div>
    <table id="sub-batch-table"
           class="display border-0 table-with-no-border dataTable no-footer w-100"
           role="grid"
           aria-describedby="sub-batch-table_info">
        {% csrf_token %}
    </table>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#sub-batch-table'),
                "{% url 'sub-batch-datatable' %}", {
                    serverSide: true,
                    processing: true,
                    searching: true,
                    autoWidth: false,
                    scrollX: false,
                }, {
                    "batch_id": "{{ object.id }}"
                }
            );
        });
        $("#search_project").on('input', function() {
            var searchvalue = $(this).val();
            var table = $("#sub-batch-table").DataTable();
            table.search(searchvalue).draw();
        });
        $(document).ready(function() {
            $('#sub-batch-table').on('xhr.dt', function(e, settings, json, xhr) {
                $("#teams_count").text(json['extra_data'][0]["no_of_teams"]);
                $("#trainees_count").text(json['extra_data'][0]["no_of_trainees"]);
            });
        });

        function deleteSubBatch(url) {
            let text = 'Are you sure do you want to delete';
            if (confirm(text) == true) {
                $('.page-loader').show();
                $.ajax({
                    type: "DELETE",
                    url: url,
                    success: function(data) {
                        $('.page-loader').hide();
                        $('#sub-batch-table').DataTable().ajax.reload();
                    },
                    error: function() {
                        $('.page-loader').hide();
                        alert("Something went wrong, please reload the page");
                    }
                });
            }
        }
    </script>
{% endblock %}

training/templates/sub_batch/update_sub_batch.html
{% extends 'layouts/base.html' %}

{% block title %}
    Update Sub Batch
{% endblock title %}

{% block header %}
    <div class="flex justify-between items-center">
        <div>
            <div class="text-dark-black text-lg mb-1 leading-none whitespace-nowrap">Update Sub Batch</div>
        </div>
        <div class=" w-full flex justify-end items-center batch-btn">
            <a href="{% url 'batch.detail' sub_batch.batch.id %}"
               class="text-white bg-gray-500 rounded inline-flex items-center px-3 py-1 mr-6 text-base font-normal">
               <span class="text-xl mr-2">x</span>
                Cancel
            </a>
            <a
                class="text-white bg-dark-blue rounded inline-flex items-center px-3 py-1 text-base font-normal cursor-pointer"
                id="update_sub_batch">
                <span class="text-xl mr-2">+</span>
                Update Sub Batch
            </a>
        </div>
    </div>
{% endblock %}

{% block body %}
    <form method="post" enctype="multipart/form-data" id="sub_batch_form">
        {% csrf_token %}
        <div class="grid grid-cols-3 gap-210">
            <div class="form-field">
                {{ form.name|show_label }}
                {{ form.name }}
                {{ form.name|show_field_errors }}
            </div>
            <div class="work-basic-dropdown form-field" id="team_dropdown">
                {{ form.team|show_label }}
                <div class="relative">{{ form.team }}</div>
                {{ form.team|show_field_errors }}
            </div>
            <div class="form-field">
                {{ form.start_date|show_label }}
                {{ form.start_date }}
                {{ form.start_date|show_field_errors }}
            </div>
            <div class="work-basic-dropdown form-field">
                {{ form.timeline|show_label }}
                <div class="relative" id="timeline-template-select">
                    <select name="timeline"
                            class="w-full block border border-primary-dark-30 rounded-md focus:outline-none focus:ring-transparent focus:ring-offset-0 h-9 p-2 dropdown_select bg-transparent w-250 timeline-input invisible"
                            required=""
                            id="id_timeline"></select>
                </div>
                {{ form.timeline|show_field_errors }}
            </div>
            <div class="work-basic-dropdown form-field">
                {{ form.primary_mentor_id|show_label }}
                <div class="relative mt-2.5">{{ form.primary_mentor_id }}</div>
                {{ form.primary_mentor_id|show_field_errors }}
            </div>
            <div class="work-basic-dropdown form-field">
                {{ form.secondary_mentor_ids|show_label }}
                <div class="relative mt-2.5">{{ form.secondary_mentor_ids }}</div>
                {{ form.secondary_mentor_ids|show_field_errors }}
            </div>
        </div>
        <div class="mt-5">
            {% if form.errors %}{{ form.non_field_errors|show_non_field_errors }}{% endif %}
        </div>
    </form>
{% endblock %}

{% block script %}
    <script>
        function update_timeline_value(initialValue = null) {
            if ($("#id_team").val()) {
                $('.page-loader').show();
                $("#id_timeline").val("");
                $.ajax({
                    type: "POST",
                    url: "{% url 'sub-batch.get_timelines' %}",
                    data: {
                        team_id: $("#id_team").val()
                    },
                    success: function(data) {
                        let selectDropdown = `<select name="timeline" class="w-full block border border-primary-dark-30 rounded-md focus:outline-none focus:ring-transparent focus:ring-offset-0 h-9 p-2 dropdown_select bg-transparent w-250 timeline-input invisible" required="" id="id_timeline"></select>`;
                        $("#timeline-template-select").empty();
                        const selectElement = $(selectDropdown);

                        if (data.length !== 0) {
                            selectElement.append(`<option value="${0}">Select a Timeline</option>`);
                            data.forEach(function(item) {
                                const option = `<option value="${item.id}" ${item.is_active ? "selected" : ""}>${item.name}</option>`;
                                selectElement.append(option);
                            });
                        }

                        $("#timeline-template-select").append(selectElement);

                        if (initialValue !== null) {
                            $("#id_timeline").attr("initialValue", initialValue);
                        }

                        dropdown_init();
                        $('.page-loader').hide();
                        $('#id_timeline').siblings().find('#show-value').html(data.find(item => item.is_active === true).name);
                    },
                    error: function(xhr, status, error) {
                        $('.page-loader').hide();
                        alert(xhr.responseJSON.message);
                    }
                });
            }
        };

        $(document).ready(function() {
            var timeline = `{{ form.timeline }}`
            let timeline_id = $(timeline).val();
            update_timeline_value(initialValue = timeline_id);
            $('#update_sub_batch').click(function(e) {
                e.preventDefault();
                $('#sub_batch_form').submit();
            })
            $("#team_dropdown").find(".multi-select-inner").css("pointer-events", "none");
            $("#id_start_date").val(moment($("#id_start_date").val()).format('DD MMM YYYY'));
        });

        $(function() {

            $('input[name="start_date"]').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                autoApply: true,
                minDate: new Date("{{ sub_batch.batch.start_date }}"),
                locale: {
                    format: 'DD MMM YYYY',
                }
            });
        });
    </script>
{% endblock %}