hubble/urls.py
"""
Hubble application url configuration
"""
from django.urls import include, path

from core.constants import ENVIRONMENT_DEVELOPMENT
from hubble import views
from hubble_report.settings import ENV_NAME

urlpatterns = [
    path("login", views.login, name="login"),
    path("signin", views.signin, name="signin"),
    path("signout", views.signout, name="signout"),
]

if ENV_NAME == ENVIRONMENT_DEVELOPMENT:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

hubble_report/urls.py
from django.urls import path

from hubble import views

urlpatterns = [path("health-check", views.health_check)]

training/urls.py
"""
Training app url configuration
"""
from django.urls import include, path

from hubble import views as sso_view
from training import view
from training.views import (
    batch,
    induction_kit,
    sub_batch,
    sub_batch_timeline,
    timeline,
    timeline_task,
    trainee_holiday,
    user_journey,
)

handler404 = view.error_404
handler500 = view.error_500

urlpatterns = [
    path("", include("hubble.urls")),
    path("", view.home, name="training.home"),
    path("hubble-sso-callback", sso_view.callback, name="callback"),
    # Induction kit
    path(
        "induction-kit",
        induction_kit.InductionKit.as_view(),
        name="induction-kit",
    ),
    path(
        "induction-kit/<text>",
        induction_kit.induction_kit_detail,
        name="induction-kit.detail",
    ),
    # Timeline Template
    path(
        "timeline-template",
        timeline.TimelineTemplate.as_view(),
        name="timeline-template",
    ),
    path(
        "timeline-datatable",
        timeline.TimelineTemplateDataTable.as_view(),
        name="timeline-template.datatable",
    ),
    path(
        "timeline-template/create",
        timeline.create_timeline_template,
        name="timeline-template.create",
    ),
    path(
        "timeline-template/<int:pk>/show",
        timeline.timeline_template_data,
        name="timeline-template.show",
    ),
    path(
        "timeline-template/<int:pk>/edit",
        timeline.update_timeline_template,
        name="timeline-template.edit",
    ),
    path(
        "timeline-template/<int:pk>/delete",
        timeline.delete_timeline_template,
        name="timeline-template.delete",
    ),
    path(
        "timeline-template/<int:pk>",
        timeline.TimelineTemplateDetails.as_view(),
        name="timeline-template.detail",
    ),
    # Timeline Task
    path(
        "timeline-task-datatable",
        timeline_task.TimelineTemplateTaskDataTable.as_view(),
        name="timeline-task.datatable",
    ),
    path(
        "timeline-task/create",
        timeline_task.create_timeline_task,
        name="timeline-task.create",
    ),
    path(
        "timeline-task/<int:pk>/show",
        timeline_task.timeline_task_data,
        name="timeline-task.show",
    ),
    path(
        "timeline-task/<int:pk>/edit",
        timeline_task.update_timeline_task,
        name="timeline-task.edit",
    ),
    path(
        "timeline-task/<int:pk>/delete",
        timeline_task.delete_timeline_task,
        name="timeline-task.delete",
    ),
    path(
        "timeline-task/reorder",
        timeline_task.update_order,
        name="timeline-task.reorder",
    ),
    # Batch
    path("batch", batch.BatchList.as_view(), name="batch"),
    path(
        "batch-datatable",
        batch.BatchDataTable.as_view(),
        name="batch.datatable",
    ),
    path("batch/create", batch.create_batch, name="batch.create"),
    path(
        "batch/<int:pk>/show",
        batch.batch_data,
        name="batch.show",
    ),
    path(
        "batch/<int:pk>/edit",
        batch.update_batch,
        name="batch.edit",
    ),
    path(
        "batch/<int:pk>/delete",
        batch.delete_batch,
        name="batch.delete",
    ),
    path(
        "batch/<int:pk>",
        batch.BatchDetails.as_view(),
        name="batch.detail",
    ),
    # Batch Holiday
    path(
        "batch/<int:pk>/holiday",
        trainee_holiday.TraineeHolidayList.as_view(),
        name="batch.holiday",
    ),
    path(
        "trainee-holiday-datatable",
        trainee_holiday.TraineeHolidayDataTable.as_view(),
        name="holiday-datatable",
    ),
    path(
        "batch/<int:pk>/holiday/create",
        trainee_holiday.TraineeHolidayCreateView.as_view(),
        name="holiday.create",
    ),
    path(
        "holiday/<int:pk>/show",
        trainee_holiday.TraineeHolidayDataView.as_view(),
        name="holiday.show",
    ),
    path(
        "holiday/<int:pk>/edit",
        trainee_holiday.TraineeHolidayUpdateView.as_view(),
        name="holiday.edit",
    ),
    path(
        "holiday/<int:pk>/delete",
        trainee_holiday.TraineeHolidayDeleteView.as_view(),
        name="holiday.delete",
    ),
    # Sub Batch
    path(
        "sub-batch-datatable",
        sub_batch.SubBatchDataTable.as_view(),
        name="sub-batch-datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch/create",
        sub_batch.create_sub_batch,
        name="sub-batch.create",
    ),
    path(
        "sub-batch/get-timeline",
        sub_batch.get_timelines,
        name="sub-batch.get_timelines",
    ),
    path(
        "sub-batch/<int:pk>/edit",
        sub_batch.update_sub_batch,
        name="sub-batch.edit",
    ),
    path(
        "sub-batch/<int:pk>",
        sub_batch.SubBatchDetail.as_view(),
        name="sub-batch.detail",
    ),
    path(
        "sub-batch/<int:pk>/delete",
        sub_batch.delete_sub_batch,
        name="sub-batch.delete",
    ),
    path(
        "sub-batch/trainees-datatable",
        sub_batch.SubBatchTraineesDataTable.as_view(),
        name="sub-batch.trainees-datatable",
    ),
    path(
        "sub-batch/trainees/add",
        sub_batch.add_trainee,
        name="trainees.add",
    ),
    path(
        "sub-batch/trainee/<int:pk>/remove",
        sub_batch.remove_trainee,
        name="trainee.remove",
    ),
    # sub_batch_timeline
    path(
        "sub-batch/<int:pk>/timeline",
        sub_batch_timeline.SubBatchTimeline.as_view(),
        name="sub-batch.timeline",
    ),
    path(
        "sub-batch/timeline-datatable",
        sub_batch_timeline.SubBatchTimelineDataTable.as_view(),
        name="sub-batch.datatable",
    ),
    path(
        "batch/<int:pk>/sub-batch-timeline/create",
        sub_batch_timeline.create_sub_batch_timeline,
        name="sub_batch.timeline.create",
    ),
    path(
        "sub-batch-timeline/<int:pk>/show",
        sub_batch_timeline.sub_batch_timeline_data,
        name="sub_batch.timeline.show",
    ),
    path(
        "sub-batch-timeline/<int:pk>/edit",
        sub_batch_timeline.update_sub_batch_timeline,
        name="sub_batch.timeline.edit",
    ),
    path(
        "sub-batch-timeline/reorder",
        sub_batch_timeline.update_task_sequence,
        name="sub_batch.timeline.reorder",
    ),
    path(
        "sub-batch-timeline/<int:pk>/delete",
        sub_batch_timeline.delete_sub_batch_timeline,
        name="sub_batch.timeline.delete",
    ),
    # user_reports_crud
    path(
        "user/<int:pk>",
        user_journey.TraineeJourneyView.as_view(),
        name="user_reports",
    ),
    path(
        "task/show-score",
        user_journey.show_task_score,
        name="task.show_score",
    ),
    path(
        "user/<int:pk>/update-score",  # TODO :: Change to task_id
        user_journey.update_task_score,
        name="user.update-score",
    ),
    path(
        "add-extension/<int:pk>",
        user_journey.add_extension,
        name="extension.create",
    ),
    path(
        "extension/<int:pk>/delete",
        user_journey.delete_extension,
        name="extension.delete",
    ),
    path("show-score-history", user_journey.get_mark_history, name="score_history"),
]

hubble/models/batch.py
"""
The Batch class is a Django model that represents a batch with a
name and a reference to the user
"""
from django.db import models

from core import db


class Batch(db.SoftDeleteWithBaseModel):
    """
    Store the batch name
    """

    name = models.CharField(max_length=250)
    start_date = models.DateField(null=True)
    created_by = models.ForeignKey("hubble.User", on_delete=models.CASCADE)

    class Meta:
        """
        Meta class for defining class behavior and properties.
        """

        db_table = "batches"

    def __str__(self):
        return str(self.name)

training/views/batch.py
"""
Django view for managing batches, including creating, updating, and
deleting batches, as well as displaying batch details
"""
import logging

from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, OuterRef, Q, Subquery
from django.db.models.functions import Coalesce
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, FormView

from core import template_utils
from core.constants import BATCH_DURATION_IN_MONTHS
from core.utils import CustomDatatable, validate_authorization
from hubble.models import Batch, Holiday, InternDetail, SubBatch, TraineeHoliday
from training.forms import BatchForm


class BatchList(LoginRequiredMixin, FormView):
    """
    Timeline Template
    """

    form_class = BatchForm
    template_name = "batch/batch_list.html"


class BatchDataTable(LoginRequiredMixin, CustomDatatable):
    """
    Batch Datatable class is used for display the batch data with defined column
    """

    model = Batch

    column_defs = [
        {"name": "id", "visible": False, "searchable": False},
        {"name": "name", "visible": True, "searchable": True},
        {
            "name": "number_of_sub_batches",
            "title": "Number of Sub Batches",
            "searchable": False,
        },
        {
            "name": "total_trainee",
            "title": "No. of Trainees",
            "visible": True,
            "searchable": False,
        },
        {
            "name": "start_date",
            "title": "Start Date",
            "visible": True,
            "searchable": False,
        },
        {
            "name": "action",
            "title": "Action",
            "visible": True,
            "searchable": False,
            "orderable": False,
            "className": "text-center",
        },
    ]

    def get_initial_queryset(self, request=None):  # pylint: disable=unused-argument
        """
        The function returns an annotated queryset with the total number of
        trainees and the number of sub-batches for each object in the model.
        """
        return self.model.objects.annotate(
            total_trainee=Count(
                "sub_batches__intern_details",
                filter=Q(sub_batches__intern_details__deleted_at__isnull=True),
            ),
            number_of_sub_batches=Coalesce(
                Subquery(
                    self.model.objects.filter(sub_batches__batch_id=OuterRef("id"))
                    .annotate(
                        number_of_sub_batches=Count(
                            "sub_batches__id",
                            filter=Q(sub_batches__deleted_at__isnull=True),
                        )
                    )
                    .values("number_of_sub_batches")
                ),
                0,
            ),
        )

    def customize_row(self, row, obj):
        """
        The function customize_row customizes a row by adding buttons for
        viewing, editing, and deleting a batch object, based on the user's permissions.
        """
        buttons = template_utils.show_button(reverse("batch.detail", args=[obj.id]))
        if self.request.user.is_admin_user:
            buttons += template_utils.edit_button(
                reverse("batch.show", args=[obj.id])
            ) + template_utils.delete_button(
                "deleteBatch('" + reverse("batch.delete", args=[obj.id]) + "')"
            )
        row["action"] = f'<div class="form-inline justify-content-center">{buttons}</div>'
        row["start_date"] = obj.start_date.strftime("%d %b %Y")
        return row


@login_required()
@validate_authorization()
def create_batch(request):
    """
    Create Batch
    """
    response_data = {}  # Initialize an empty dictionary
    if request.method == "POST":
        form = BatchForm(request.POST)
        if form.is_valid():  # Check if the valid or not
            batch = form.save(commit=False)
            batch.created_by = request.user
            batch.save()
            start_date = batch.start_date
            end_date = start_date + relativedelta(months=BATCH_DURATION_IN_MONTHS)
            holidays = Holiday.objects.filter(date_of_holiday__range=(start_date, end_date))
            trainee_holidays = [
                TraineeHoliday(
                    batch_id=batch.id,
                    date_of_holiday=holiday.date_of_holiday,
                    month_year=holiday.month_year,
                    updated_by=request.user,
                    reason=holiday.reason,
                    allow_check_in=holiday.allow_check_in,
                    national_holiday=holiday.national_holiday,
                )
                for holiday in holidays
            ]
            TraineeHoliday.objects.bulk_create(trainee_holidays)
            return JsonResponse({"status": "success"})
        field_errors = form.errors.as_json()
        non_field_errors = form.non_field_errors().as_json()
        response_data = {
            "status": "error",
            "field_errors": field_errors,
            "non_field_errors": non_field_errors,
        }
    return JsonResponse(response_data)


@login_required()
@validate_authorization()
def batch_data(request, pk):  # pylint: disable=unused-argument
    """
    The function batch_data retrieves batch data from the database and
    returns it as a JSON response.
    """
    try:
        data = {
            "batch": model_to_dict(get_object_or_404(Batch, id=pk))
        }  # Covert django queryset object to dict,which can be easily
        # serialized and sent as a JSON response
        return JsonResponse(data, safe=False)
    except Exception as exception:
        logging.error("An error has occured while fetching the batch data \n%e", exception)
        return JsonResponse({"message": "Error while getting the data!"}, status=500)


@login_required()
@validate_authorization()
def update_batch(request, pk):
    """
    The function update_batch updates a batch object with the data provided
    in the request and returns a JSON response indicating the success or
    failure of the update operation.
    """
    batch = get_object_or_404(Batch, id=pk)
    form = BatchForm(request.POST, instance=batch)
    if form.is_valid():  # Check if the valid or not
        form.save()
        return JsonResponse({"status": "success"})
    field_errors = form.errors.as_json()
    non_field_errors = form.non_field_errors().as_json()
    return JsonResponse(
        {
            "status": "error",
            "field_errors": field_errors,
            "non_field_errors": non_field_errors,
        }
    )


@login_required()
@validate_authorization()
@require_http_methods(
    ["DELETE"]
)  # This decorator ensures that the view function is only accessible through the
# DELETE HTTP method
def delete_batch(request, pk):  # pylint: disable=unused-argument
    """
    Delete Batch
    Soft delete the batch and record the deletion time in deleted_at field
    """
    try:
        batch = get_object_or_404(Batch, id=pk)
        intern_details = list(batch.sub_batches.all().values_list("id", flat=True))
        TraineeHoliday.bulk_delete({"batch_id": pk})
        SubBatch.bulk_delete({"batch_id": pk})
        InternDetail.bulk_delete({"sub_batch_id__in": intern_details})
        batch.delete()
        return JsonResponse({"message": "Batch deleted succcessfully"})
    except Exception as exception:
        logging.error("An error has occured while deleting the batch data \n%e", exception)
        return JsonResponse({"message": "Error while deleting Batch!"}, status=500)


class BatchDetails(LoginRequiredMixin, DetailView):
    """
    BatchDetails class is a Django view that displays the details of a Batch model object
    """

    model = Batch
    template_name = "sub_batch/sub_batch.html"

training/views/induction_kit.py
"""
Django view and a function for serving PDF files from a static folder, with 
authentication required for accessing the view
"""
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.views.generic import TemplateView


class InductionKit(LoginRequiredMixin, TemplateView):
    """
    Induction Kit
    """

    template_name = "induction_kit.html"
    # Getting the list of pdf files in the static folder.
    static_path = list(settings.STATICFILES_DIRS)
    extra_context = {
        "pdf_files": [
            file
            for file in os.listdir(f"{static_path[0]}/training/pdf")
            if os.path.splitext(file)[1] == ".pdf"
        ],
    }


@login_required()
def induction_kit_detail(request, text):  # pylint: disable=unused-argument
    """
    Induction Kit Detail
    """
    static_path = list(settings.STATICFILES_DIRS)
    file_path = f"{static_path[0]}/training/pdf/{text}"
    return FileResponse(open(file_path, "rb"), content_type="application/pdf")

training/templates/batch/batch_list.html
{% extends 'layouts/base.html' %}

{% block title %}
    Batch
{% endblock title %}

{% block header %}
    <div class="flex justify-between items-center">
        <div>
            <div class="text-dark-black text-lg mb-1 leading-none">Batch List</div>
            <div class="text-dark-black-50 text-sm">List of Batches</div>
        </div>
        {% if request.user.is_admin_user %}
            <button class="text-white bg-dark-blue rounded inline-flex items-center px-3 py-1 text-base font-normal"
                    onclick="openModal()">
                <span class="text-xl mr-2">+</span>
                Create Batch
            </button>
        {% endif %}
    </div>
{% endblock %}

{% block body %}
    <div class="jquery-modal current hidden batch-model" id="modal">
        <div class="modal py-5 rounded-xl mr-5 mt-9 bg-white  jquery-modal-body">
            <p class="font-semibold text-lg mb-10" id="open_modal">Create Batch</p>
            <form method="post" class="timeline-form" id="timeline-create-form">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group mb-7" id="{{ form.name.label|lower }}_group">
                        {{ form.name|show_label }}
                        {{ form.name }}
                    </div>
                    <div class="form-group mb-7"
                         id="{{ form.start_date.label|lower|replace_spaces }}_group">
                        {{ form.start_date|show_label }}
                        {{ form.start_date }}
                    </div>
                </div>
                <div id="non_field_error"></div>
                <div class="text-center mt-10">
                    <a class="cursor-pointer inline-block align-middle border border-grey px-8 py-2 rounded mr-6"
                       onclick="closeModal('modal')">Close</a>
                    <a class="cursor-pointer inline-block align-middle text-white bg-dark-blue rounded inline-flex items-center rounded px-8 py-2 text-base font-normal"
                       id="submit-btn">Submit</a>
                </div>
            </form>
        </div>
    </div>
    <div class="flex mb-7 items-center">
        <div class="relative mr-5" id="batch-table_filter">
            <input type="text"
                   value=""
                   name="search_project"
                   placeholder="Search by Name"
                   class="w-397 h-10 pl-11 pr-2.5 py-3 text-sm rounded-xl text-dark-black-50 font-normal bg-mild-white focus:outline-none focus:ring-transparent focus:ring-offset-0"
                   id="search_project">
            <span class="absolute top-2 left-2"><span class="hbl hbl-search-icon text-dark-black-50 text-2xl"></span></span>
        </div>
    </div>
    <table id="batch-table" class="display border-0 table-with-no-border dataTable no-footer"
        role="grid" aria-describedby="batch-table_info">
    </table>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#batch-table'),
                "{% url 'batch.datatable' %}", {
                    serverSide: true,
                    processing: true,
                    autoWidth: false,
                    scrollX: false,
                },
            );
        });

        $("#search_project").on('input', function() {
            var searchvalue = $(this).val();
            var table = $("#batch-table").DataTable();
            table.search(searchvalue).draw();
        });

        function openModal() {
            start_date_picker();
            openBaseModal();
            $("#open_modal").text("Create Batch");
            $('#id_name').val('');
            $('#submit-btn').attr("onclick", "createBatch()");
        }

        function createBatch() {
            $('.page-loader').show();
            $.ajax({
                type: "POST",
                url: "{% url 'batch.create' %}",
                data: {
                    name: $('#id_name').val(),
                    start_date: $('#id_start_date').val(),
                },
                success: function(data) {
                    $('.page-loader').hide();
                    if (data.status === 'success') {
                        $('#batch-table').DataTable().ajax.reload();
                        closeModal('modal');
                    } else {
                        removeErrors();
                        renderFormError(data);
                    }
                },
                error: function() {
                    $('.page-loader').hide();
                    alert("Something went wrong");
                },
            });
        }

        function openUpdateModel(url) {
            $('.page-loader').show();
            removeErrors();
            $("#open_modal").text("Update Batch");
            $.ajax({
                type: "GET",
                url: url,
                success: function(data) {
                    $('.page-loader').hide();
                    $('#id_name').val(data.batch.name);
                    $('#batch_id').val(data.batch.id);
                    start_date_picker(data.batch.start_date);
                    $('#submit-btn').attr("onclick", "updateBatch(" + data.batch.id + ")");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert(jqXHR.responseJSON.message);
                    $('.page-loader').hide();
                },
            });
            document.getElementById("modal").classList.remove("hidden");
            document.getElementById("modal").classList.add("blocker");
        }

        function updateBatch(id) {
            $('.page-loader').show();
            $.ajax({
                type: "POST",
                url: "batch/" + id + "/edit", //TODO
                data: {
                    name: $('#id_name').val(),
                    start_date: $('#id_start_date').val(),
                },
                success: function(data) {
                    $('.page-loader').hide();
                    if (data.status === 'success') {
                        $('#batch-table').DataTable().ajax.reload();
                        closeModal('modal');
                    } else {
                        removeErrors();
                        renderFormError(data);
                    }
                },
                error: function() {
                    $('.page-loader').hide();
                    alert("Something went wrong");
                },
            });
        }

        function deleteBatch(url) {
            let text = 'Are you sure do you want to delete';
            if (confirm(text) == true) {
                $('.page-loader').show();
                $.ajax({
                    type: "DELETE",
                    url: url,
                    success: function(data) {
                        $('.page-loader').hide();
                        $('#batch-table').DataTable().ajax.reload();
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        alert(jqXHR.responseJSON.message);
                        $('.page-loader').hide();
                    },
                });
            }
        }

        function start_date_picker(date = null) {
            if (date == null) {
                date = moment();
            }
            $('input[name="start_date"]').daterangepicker({
                singleDatePicker: true,
                autoApply: true,
                startDate: new Date(date),
                locale: {
                    format: 'DD MMM YYYY',
                }
            });
        }

        $(function() {
            start_date_picker();
        });
    </script>
{% endblock %}